// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"

interface WeatherForecast {
    date: string;
    temperatureC: number;
    temperatureF: number;
    summary: string;
}

interface WeatherState {
    forecasts: WeatherForecast[];
    loading: boolean;
    error: string | null;
}

const initialState: WeatherState = {
    forecasts: [],
    loading: false,
    error: null,
};

export const weatherApiSlice = createApi({
    reducerPath: 'weatherApi',
    baseQuery: fetchBaseQuery({ baseUrl: 'https://localhost:7062' }),
    endpoints: (builder) => ({
        getWeatherForecasts: builder.query<WeatherForecast[], void>({
            query: () => '/WeatherForecast',
        }),
    }),
});


// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetWeatherForecastsQuery } = weatherApiSlice
